version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ./influxdb/data:/var/lib/influxdb
    networks:
      proxy:
        ipv4_address: 172.23.0.13
    restart: always

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      proxy:
        ipv4_address: 172.23.0.14
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./grafana/data:/var/lib/grafana
    environment:
      - "GF_SMTP_ENABLED=true"
      - "GF_SMTP_HOST=smtp.gmail.com:587"
      - "GF_SMTP_USER=hbnet.alerts@gmail.com"
      - "GF_SMTP_PASSWORD=St@3dl3r123@@"
      - "GF_SMTP_FROM_ADDRESS=grafana@hbnet.co.za"
      - "GF_SERVER_ROOT_URL=https://grafana.hbnet.co.za"
      - "GF_INSTALL_PLUGINS=raintank-worldping-app,grafana-worldmap-panel"
    networks:
      proxy:
        ipv4_address: 172.23.0.15
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.hbnet.co.za`)"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.hbnet.co.za`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"


networks:
  proxy:
    external: true